/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSolutionsRouteImport } from './routes/_authenticated/solutions'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStaffTicketsRouteImport } from './routes/_authenticated/staff.tickets'
import { Route as AuthenticatedStaffSolutionsRouteImport } from './routes/_authenticated/staff.solutions'
import { Route as AuthenticatedStaffSectorsRouteImport } from './routes/_authenticated/staff.sectors'
import { Route as AuthenticatedStaffAnalyticsRouteImport } from './routes/_authenticated/staff.analytics'
import { Route as AuthenticatedStaffTicketsIdRouteImport } from './routes/_authenticated/staff.tickets.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolutionsRoute = AuthenticatedSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffTicketsRoute =
  AuthenticatedStaffTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffSolutionsRoute =
  AuthenticatedStaffSolutionsRouteImport.update({
    id: '/solutions',
    path: '/solutions',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffSectorsRoute =
  AuthenticatedStaffSectorsRouteImport.update({
    id: '/sectors',
    path: '/sectors',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAnalyticsRoute =
  AuthenticatedStaffAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffTicketsIdRoute =
  AuthenticatedStaffTicketsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedStaffTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/solutions': typeof AuthenticatedSolutionsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRoute
  '/staff/analytics': typeof AuthenticatedStaffAnalyticsRoute
  '/staff/sectors': typeof AuthenticatedStaffSectorsRoute
  '/staff/solutions': typeof AuthenticatedStaffSolutionsRoute
  '/staff/tickets': typeof AuthenticatedStaffTicketsRouteWithChildren
  '/staff/tickets/$id': typeof AuthenticatedStaffTicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/solutions': typeof AuthenticatedSolutionsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRoute
  '/staff/analytics': typeof AuthenticatedStaffAnalyticsRoute
  '/staff/sectors': typeof AuthenticatedStaffSectorsRoute
  '/staff/solutions': typeof AuthenticatedStaffSolutionsRoute
  '/staff/tickets': typeof AuthenticatedStaffTicketsRouteWithChildren
  '/staff/tickets/$id': typeof AuthenticatedStaffTicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/solutions': typeof AuthenticatedSolutionsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/staff/analytics': typeof AuthenticatedStaffAnalyticsRoute
  '/_authenticated/staff/sectors': typeof AuthenticatedStaffSectorsRoute
  '/_authenticated/staff/solutions': typeof AuthenticatedStaffSolutionsRoute
  '/_authenticated/staff/tickets': typeof AuthenticatedStaffTicketsRouteWithChildren
  '/_authenticated/staff/tickets/$id': typeof AuthenticatedStaffTicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/dashboard'
    | '/perfil'
    | '/solutions'
    | '/staff'
    | '/tickets'
    | '/staff/analytics'
    | '/staff/sectors'
    | '/staff/solutions'
    | '/staff/tickets'
    | '/staff/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/dashboard'
    | '/perfil'
    | '/solutions'
    | '/staff'
    | '/tickets'
    | '/staff/analytics'
    | '/staff/sectors'
    | '/staff/solutions'
    | '/staff/tickets'
    | '/staff/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/perfil'
    | '/_authenticated/solutions'
    | '/_authenticated/staff'
    | '/_authenticated/tickets'
    | '/_authenticated/staff/analytics'
    | '/_authenticated/staff/sectors'
    | '/_authenticated/staff/solutions'
    | '/_authenticated/staff/tickets'
    | '/_authenticated/staff/tickets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solutions': {
      id: '/_authenticated/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof AuthenticatedSolutionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/tickets': {
      id: '/_authenticated/staff/tickets'
      path: '/tickets'
      fullPath: '/staff/tickets'
      preLoaderRoute: typeof AuthenticatedStaffTicketsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/solutions': {
      id: '/_authenticated/staff/solutions'
      path: '/solutions'
      fullPath: '/staff/solutions'
      preLoaderRoute: typeof AuthenticatedStaffSolutionsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/sectors': {
      id: '/_authenticated/staff/sectors'
      path: '/sectors'
      fullPath: '/staff/sectors'
      preLoaderRoute: typeof AuthenticatedStaffSectorsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/analytics': {
      id: '/_authenticated/staff/analytics'
      path: '/analytics'
      fullPath: '/staff/analytics'
      preLoaderRoute: typeof AuthenticatedStaffAnalyticsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/tickets/$id': {
      id: '/_authenticated/staff/tickets/$id'
      path: '/$id'
      fullPath: '/staff/tickets/$id'
      preLoaderRoute: typeof AuthenticatedStaffTicketsIdRouteImport
      parentRoute: typeof AuthenticatedStaffTicketsRoute
    }
  }
}

interface AuthenticatedStaffTicketsRouteChildren {
  AuthenticatedStaffTicketsIdRoute: typeof AuthenticatedStaffTicketsIdRoute
}

const AuthenticatedStaffTicketsRouteChildren: AuthenticatedStaffTicketsRouteChildren =
  {
    AuthenticatedStaffTicketsIdRoute: AuthenticatedStaffTicketsIdRoute,
  }

const AuthenticatedStaffTicketsRouteWithChildren =
  AuthenticatedStaffTicketsRoute._addFileChildren(
    AuthenticatedStaffTicketsRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffAnalyticsRoute: typeof AuthenticatedStaffAnalyticsRoute
  AuthenticatedStaffSectorsRoute: typeof AuthenticatedStaffSectorsRoute
  AuthenticatedStaffSolutionsRoute: typeof AuthenticatedStaffSolutionsRoute
  AuthenticatedStaffTicketsRoute: typeof AuthenticatedStaffTicketsRouteWithChildren
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffAnalyticsRoute: AuthenticatedStaffAnalyticsRoute,
  AuthenticatedStaffSectorsRoute: AuthenticatedStaffSectorsRoute,
  AuthenticatedStaffSolutionsRoute: AuthenticatedStaffSolutionsRoute,
  AuthenticatedStaffTicketsRoute: AuthenticatedStaffTicketsRouteWithChildren,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSolutionsRoute: typeof AuthenticatedSolutionsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSolutionsRoute: AuthenticatedSolutionsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
